- name: Install and start web server
  hosts: webserver
  become: yes
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present

    - name: Start apache2
      service:
        name: apache2
        state: started
        enabled: yes

- name: Install Docker on Debian
  hosts: webserver
  become: yes
  tasks:
    - name: Update APT package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
