- name: Install Docker on Debian
  hosts: webserver
  become: yes
  tasks:
    - name: Update APT package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Check if Docker is already installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: docker_installed.rc != 0

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
      when: docker_installed.rc != 0

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
